# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       qmf
Summary:    Qt Messaging Framework (QMF)
Version:    1.0.7~2011w13
Release:    1
Group:      System/Libraries
License:    LGPLv2.1 with exception or GPLv3
URL:        http://qt.gitorious.org/qt-labs/messagingframework
Source0:    %{name}-%{version}.tar.bz2
Source1:    qmf.sh
Source2:    messageserver.desktop
Source100:  qmf.yaml
Patch0:     fix_docs_installation.patch
Patch1:     fix_plugins_installation.patch
Patch2:     fix_tests_installation.patch
Patch3:     no_rpath_tests_benchmarks.patch
Patch4:     add_headers.patch
Patch5:     mallochook.patch
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  qt-devel-tools
BuildRequires:  fdupes


%description
The Qt Messaging Framework, QMF, consists of a C++ library and daemon server
process that can be used to build email clients, and more generally software
that interacts with email and mail servers.



%package devel
Summary:    Qt Messaging Framework (QMF) - development files
Group:      Development/Libraries
Requires:   libqmfmessageserver1 = %{version}
Requires:   libqmfutil1 = %{version}
Requires:   libqmfclient1 = %{version}

%description devel
The Qt Messaging Framework, QMF, consists of a C++ library and daemon server
process that can be used to build email clients, and more generally software
that interacts with email and mail servers.

This package contains the development files needed to build Qt applications
using Qt Messaging Framework libraries.


%package -n libqmfmessageserver1
Summary:    Qt Messaging Framework (QMF) message server support library
Group:      System/Libraries
Requires:   libqtsql4-sqlite
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqmfmessageserver1
The Qt Messaging Framework, QMF, consists of a C++ library and daemon server
process that can be used to build email clients, and more generally software
that interacts with email and mail servers.

The MessageServer application is a daemon, designed to run continuously while
providing services to client applications. It provides messaging transport
functionality, communicating with external servers on behalf of Messaging
Framework client applications. New types of messaging (such as Instant
Messages or video messages) can be handled by the server application without
modification to existing client applications.

This package contains:
 - the message server support library. It provides assistance in developing GUI
   clients that access messaging data.
 - a server application supporting multiple messaging transport mechanisms.


%package -n libqmfutil1
Summary:    Qt Messaging Framework (QMF) messaging client utility library
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqmfutil1
The Qt Messaging Framework, QMF, consists of a C++ library and daemon server
process that can be used to build email clients, and more generally software
that interacts with email and mail servers.

This package contains the messaging client utility library. It provides
assistance in developing plugins for the Message Server daemon.


%package -n libqmfclient1
Summary:    Qt Messaging Framework (QMF) client library
Group:      System/Libraries
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description -n libqmfclient1
The Qt Messaging Framework, QMF, consists of a C++ library and daemon server
process that can be used to build email clients, and more generally software
that interacts with email and mail servers.

The Client library provides classes giving access to all messages stored on
the device, via a uniform interface. It simplifies the task of creating
messaging client applications, and permits other Messaging Framework
applications to interact with messaging data where appropriate. New types of
messages can be supported by the library without modification to existing
client applications.

This package contains a library for developing applications that work with
messages.


%package examples
Summary:    Qt Messaging Framework (QMF) examples
Group:      System/X11

%description examples
The Qt Messaging Framework, QMF, consists of a C++ library and daemon server
process that can be used to build email clients, and more generally software
that interacts with email and mail servers.

The Messages example client application provides an implementation of standard
functionality for creating and viewing messages.

This package contains an example client application supporting common
messaging functionality.


%package tests
Summary:    Qt Messaging Framework (QMF) tests
Group:      System/X11

%description tests
The Qt Messaging Framework, QMF, consists of a C++ library and daemon server
process that can be used to build email clients, and more generally software
that interacts with email and mail servers.

This package contains the tests for Qt Messaging Framework (QMF).


%package doc
Summary:    Qt Messaging Framework (QMF) - documentation
Group:      Documentation
BuildArch:    noarch

%description doc
The Qt Messaging Framework, QMF, consists of a C++ library and daemon server
process that can be used to build email clients, and more generally software
that interacts with email and mail servers.

This package contains the documentation for Qt Messaging Framework (QMF).


%package doc-html
Summary:    Qt Messaging Framework (QMF) - documentation (HTML format)
Group:      Documentation
BuildArch:    noarch

%description doc-html
The Qt Messaging Framework, QMF, consists of a C++ library and daemon server
process that can be used to build email clients, and more generally software
that interacts with email and mail servers.

This package contains the documentation for Qt Messaging Framework (QMF) in
HTML format.



%prep
%setup -q -n %{name}-%{version}

# fix_docs_installation.patch
%patch0 -p1
# fix_plugins_installation.patch
%patch1 -p1
# fix_tests_installation.patch
%patch2 -p1
# no_rpath_tests_benchmarks.patch
%patch3 -p1
# add_headers.patch
%patch4 -p1
# mallochook.patch
%patch5 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake  \
    QMF_INSTALL_ROOT=%{_prefix} \
    CONFIG+=syslog

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install
mkdir -p %{buildroot}%{_sysconfdir}/profile.d
cp -a %{SOURCE1} %{buildroot}%{_sysconfdir}/profile.d
mkdir -p %{buildroot}%{_sysconfdir}/xdg/autostart
cp -a %{SOURCE2} %{buildroot}%{_sysconfdir}/xdg/autostart


# >> install post
# << install post
%fdupes  %{buildroot}/%{_includedir}










%post -n libqmfmessageserver1 -p /sbin/ldconfig

%postun -n libqmfmessageserver1 -p /sbin/ldconfig


%post -n libqmfutil1 -p /sbin/ldconfig

%postun -n libqmfutil1 -p /sbin/ldconfig


%post -n libqmfclient1 -p /sbin/ldconfig

%postun -n libqmfclient1 -p /sbin/ldconfig















%files devel
%defattr(-,root,root,-)
# >> files devel
%{_includedir}/qmfmessageserver/QMailAuthenticator
%{_includedir}/qmfmessageserver/QMailMessageClassifier
%{_includedir}/qmfmessageserver/QMailMessageService
%{_includedir}/qmfmessageserver/QMailMessageServiceConfigurator
%{_includedir}/qmfmessageserver/QMailMessageServiceEditor
%{_includedir}/qmfmessageserver/QMailMessageServiceFactory
%{_includedir}/qmfmessageserver/QMailMessageServicePlugin
%{_includedir}/qmfmessageserver/QMailMessageSink
%{_includedir}/qmfmessageserver/QMailMessageSource
%{_includedir}/qmfmessageserver/QMailServiceConfiguration
%{_includedir}/qmfmessageserver/QMailTransport
%{_includedir}/qmfmessageserver/qmail*.h
%{_includedir}/qmfclient/MailId
%{_includedir}/qmfclient/QMailAccount
%{_includedir}/qmfclient/QMailAccountConfiguration
%{_includedir}/qmfclient/QMailAccountId
%{_includedir}/qmfclient/QMailAccountKey
%{_includedir}/qmfclient/QMailAccountListModel
%{_includedir}/qmfclient/QMailAccountMessageSet
%{_includedir}/qmfclient/QMailAccountSortKey
%{_includedir}/qmfclient/QMailAddress
%{_includedir}/qmfclient/QMailBase64Codec
%{_includedir}/qmfclient/QMailCodec
%{_includedir}/qmfclient/QMailContentManager
%{_includedir}/qmfclient/QMailContentManagerFactory
%{_includedir}/qmfclient/QMailContentManagerPlugin
%{_includedir}/qmfclient/QMailFilterMessageSet
%{_includedir}/qmfclient/QMailFolder
%{_includedir}/qmfclient/QMailFolderId
%{_includedir}/qmfclient/QMailFolderKey
%{_includedir}/qmfclient/QMailFolderMessageSet
%{_includedir}/qmfclient/QMailFolderSortKey
%{_includedir}/qmfclient/QMailLineEndingCodec
%{_includedir}/qmfclient/QMailMessage
%{_includedir}/qmfclient/QMailMessageBody
%{_includedir}/qmfclient/QMailMessageContentDisposition
%{_includedir}/qmfclient/QMailMessageContentType
%{_includedir}/qmfclient/QMailMessageHeaderField
%{_includedir}/qmfclient/QMailMessageId
%{_includedir}/qmfclient/QMailMessageKey
%{_includedir}/qmfclient/QMailMessageListModel
%{_includedir}/qmfclient/QMailMessageMetaData
%{_includedir}/qmfclient/QMailMessagePart
%{_includedir}/qmfclient/QMailMessagePartContainer
%{_includedir}/qmfclient/QMailMessageRemovalRecord
%{_includedir}/qmfclient/QMailMessageServer
%{_includedir}/qmfclient/QMailMessageSet
%{_includedir}/qmfclient/QMailMessageSetContainer
%{_includedir}/qmfclient/QMailMessageSetModel
%{_includedir}/qmfclient/QMailMessageSortKey
%{_includedir}/qmfclient/QMailNewEmailHandler
%{_includedir}/qmfclient/QMailNewMessageHandler
%{_includedir}/qmfclient/QMailPassThroughCodec
%{_includedir}/qmfclient/QMailQuotedPrintableCodec
%{_includedir}/qmfclient/QMailRetrievalAction
%{_includedir}/qmfclient/QMailSearchAction
%{_includedir}/qmfclient/QMailServiceAction
%{_includedir}/qmfclient/QMailStorageAction
%{_includedir}/qmfclient/QMailStore
%{_includedir}/qmfclient/QMailTimeStamp
%{_includedir}/qmfclient/QMailTransmitAction
%{_includedir}/qmfclient/QPrivatelyImplemented
%{_includedir}/qmfclient/QPrivatelyNoncopyable
%{_includedir}/qmfclient/ServiceConfiguration
%{_includedir}/qmfclient/Status
%{_includedir}/qmfclient/qloggers.h
%{_includedir}/qmfclient/qlogsystem.h
%{_includedir}/qmfclient/qmail*.h
%{_includedir}/qmfclient/qprivateimplementation.h
%{_includedir}/qmfclient/qprivateimplementationdef.h
%{_libdir}/libqmfmessageserver.prl
%{_libdir}/libqmfmessageserver.so
%{_libdir}/libqmfutil.so
%{_libdir}/libqmfclient.prl
%{_libdir}/libqmfclient.so
%{_libdir}/pkgconfig/qmfmessageserver.pc
%{_libdir}/pkgconfig/qmfclient.pc
# << files devel

%files -n libqmfmessageserver1
%defattr(-,root,root,-)
# >> files libqmfmessageserver1
%config %{_sysconfdir}/profile.d/%{name}.sh
%config %{_sysconfdir}/xdg/autostart/messageserver.desktop
%{_bindir}/messageserver
%{_libdir}/libqmfmessageserver.so.*
%{_libdir}/qmf/plugins/messageservices/libimap.so
%{_libdir}/qmf/plugins/messageservices/libpop.so
%{_libdir}/qmf/plugins/messageservices/libqmfsettings.so
%{_libdir}/qmf/plugins/messageservices/libsmtp.so
# << files libqmfmessageserver1

%files -n libqmfutil1
%defattr(-,root,root,-)
# >> files libqmfutil1
%{_libdir}/libqmfutil.so.*
# << files libqmfutil1

%files -n libqmfclient1
%defattr(-,root,root,-)
# >> files libqmfclient1
%{_libdir}/libqmfclient.so.*
%{_libdir}/qmf/plugins/contentmanagers/libqmfstoragemanager.so
# << files libqmfclient1

%files examples
%defattr(-,root,root,-)
# >> files examples
%{_bindir}/messagingaccounts
%{_bindir}/qtmail
%{_bindir}/serverobserver
%{_libdir}/qmf/plugins/composers/libemailcomposer.so
%{_libdir}/qmf/plugins/viewers/libgenericviewer.so
# << files examples

%files tests
%defattr(-,root,root,-)
# >> files tests
%{_libdir}/qmf/tests/testdata/PyBanner048.gif
%{_libdir}/qmf/tests/testdata/audiotest.au
%{_libdir}/qmf/tests/testdata/msg_01.txt
%{_libdir}/qmf/tests/testdata/msg_01a.txt
%{_libdir}/qmf/tests/testdata/msg_02.txt
%{_libdir}/qmf/tests/testdata/msg_03.txt
%{_libdir}/qmf/tests/testdata/msg_04.txt
%{_libdir}/qmf/tests/testdata/msg_05.txt
%{_libdir}/qmf/tests/testdata/msg_06.txt
%{_libdir}/qmf/tests/testdata/msg_07.txt
%{_libdir}/qmf/tests/testdata/msg_08.txt
%{_libdir}/qmf/tests/testdata/msg_09.txt
%{_libdir}/qmf/tests/testdata/msg_10.txt
%{_libdir}/qmf/tests/testdata/msg_11.txt
%{_libdir}/qmf/tests/testdata/msg_12.txt
%{_libdir}/qmf/tests/testdata/msg_12a.txt
%{_libdir}/qmf/tests/testdata/msg_13.txt
%{_libdir}/qmf/tests/testdata/msg_14.txt
%{_libdir}/qmf/tests/testdata/msg_15.txt
%{_libdir}/qmf/tests/testdata/msg_16.txt
%{_libdir}/qmf/tests/testdata/msg_17.txt
%{_libdir}/qmf/tests/testdata/msg_18.txt
%{_libdir}/qmf/tests/testdata/msg_19.txt
%{_libdir}/qmf/tests/testdata/msg_20.txt
%{_libdir}/qmf/tests/testdata/msg_21.txt
%{_libdir}/qmf/tests/testdata/msg_22.txt
%{_libdir}/qmf/tests/testdata/msg_23.txt
%{_libdir}/qmf/tests/testdata/msg_24.txt
%{_libdir}/qmf/tests/testdata/msg_25.txt
%{_libdir}/qmf/tests/testdata/msg_26.txt
%{_libdir}/qmf/tests/testdata/msg_27.txt
%{_libdir}/qmf/tests/testdata/msg_28.txt
%{_libdir}/qmf/tests/testdata/msg_29.txt
%{_libdir}/qmf/tests/testdata/msg_30.txt
%{_libdir}/qmf/tests/testdata/msg_31.txt
%{_libdir}/qmf/tests/testdata/msg_32.txt
%{_libdir}/qmf/tests/testdata/msg_33.txt
%{_libdir}/qmf/tests/testdata/msg_34.txt
%{_libdir}/qmf/tests/testdata/msg_35.txt
%{_libdir}/qmf/tests/testdata/msg_36.txt
%{_libdir}/qmf/tests/testdata/msg_37.txt
%{_libdir}/qmf/tests/testdata/msg_38.txt
%{_libdir}/qmf/tests/testdata/msg_39.txt
%{_libdir}/qmf/tests/testdata/msg_40.txt
%{_libdir}/qmf/tests/testdata/msg_41.txt
%{_libdir}/qmf/tests/testdata/msg_42.txt
%{_libdir}/qmf/tests/testdata/msg_43.txt
%{_libdir}/qmf/tests/testdata/msg_44.txt
%{_libdir}/qmf/tests/tst_longstring
%{_libdir}/qmf/tests/tst_messageserver
%{_libdir}/qmf/tests/tst_python_email
%{_libdir}/qmf/tests/tst_qmailaddress
%{_libdir}/qmf/tests/tst_qmailcodec
%{_libdir}/qmf/tests/tst_qmailmessage
%{_libdir}/qmf/tests/tst_qmailmessagebody
%{_libdir}/qmf/tests/tst_qmailmessageheader
%{_libdir}/qmf/tests/tst_qmailmessagepart
%{_libdir}/qmf/tests/tst_qmailstore
%{_libdir}/qmf/tests/tst_qmailstorekeys
%{_libdir}/qmf/tests/tst_qprivateimplementation
# << files tests

%files doc
%defattr(-,root,root,-)
# >> files doc
%doc %{_docdir}/qmf/qch/qmf.qch
# << files doc

%files doc-html
%defattr(-,root,root,-)
# >> files doc-html
%doc %{_docdir}/qmf/html/*
# << files doc-html

